## Travis CI Integration

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild NFaker.sln
  - nunit-console FFaker.net.tests/bin/Debug/NFaker.Tests.dll
